local L1UI, E, L, V, P, G = unpack(select(2, ...))

-- DBM profile setup
function L1UI:GetDBMProfile()

	DBM:CreateProfile("Luckyone")

	DBM_AllSavedOptions = {
		["Luckyone"] = {
			["DontShowFarWarnings"] = true,
			["ChosenVoicePack"] = "VEM",
			["DontShowHudMap2"] = true,
			["AlwaysPlayVoice"] = false,
			["ShowSWarningsInChat"] = false,
			["RangeFrameRadarY"] = 0.9996873736381531,
			["DontRestoreIcons"] = false,
			["DontShowNameplateIcons"] = true,
			["CoreSavedRevision"] = 20210127052658,
			["RangeFrameX"] = 416.0001525878906,
			["RangeFrameY"] = 15.99973392486572,
			["FilterInterruptNoteName"] = false,
			["EnableModels"] = false,
			["SpecialWarningFlashAlph3"] = 0.4,
			["ArrowPoint"] = "TOP",
			["SWarnNameInNote"] = true,
			["FakeBWVersion"] = true,
			["InfoFramePoint"] = "BOTTOMRIGHT",
			["EventSoundMusicCombined"] = false,
			["SpecialWarningFlashCol2"] = {
				1, -- [1]
				0.5, -- [2]
				0, -- [3]
			},
			["WarningAlphabetical"] = true,
			["WarningFont"] = "Interface\\AddOns\\ElvUI\\Media\\Fonts\\Expressway.ttf",
			["CheckGear"] = false,
			["SpecialWarningX"] = 0,
			["WorldBossAlert"] = false,
			["DontShowPT2"] = false,
			["MoviesSeen"] = {
			},
			["ShowQueuePop"] = true,
			["ShowAllVersions"] = true,
			["DebugMode"] = false,
			["DontShowTargetAnnouncements"] = true,
			["ShowWarningsInChat"] = false,
			["ShowReminders"] = true,
			["SpecialWarningFontCol"] = {
				1, -- [1]
				0.7, -- [2]
				0, -- [3]
			},
			["InfoFrameFontStyle"] = "OUTLINE",
			["WarningFontStyle"] = "OUTLINE",
			["EventSoundEngage2"] = "None",
			["InfoFrameY"] = 1.000015616416931,
			["ChatFrame"] = "DEFAULT_CHAT_FRAME",
			["WarningIconRight"] = true,
			["UseSoundChannel"] = "Master",
			["RangeFrameRadarX"] = 415.9999389648438,
			["ShowRespawn"] = true,
			["EventSoundWipe"] = "None",
			["InfoFrameCols"] = 0,
			["AlwaysShowSpeedKillTimer2"] = false,
			["FilterDispel"] = true,
			["ShowGuildMessagesPlus"] = false,
			["LFDEnhance"] = true,
			["BadTimerAlert"] = false,
			["DontShowPTNoID"] = true,
			["HideGarrisonToasts"] = false,
			["RangeFramePoint"] = "BOTTOMLEFT",
			["SpecialWarningFontShadow"] = true,
			["EventMusicMythicFilter"] = true,
			["HideBossEmoteFrame2"] = true,
			["NPAuraSize"] = 40,
			["HideObjectivesFrame"] = true,
			["SpecialWarningShortText"] = true,
			["DontShowPTText"] = false,
			["SpecialWarningFontSize2"] = 35,
			["SpecialWarningFlashCol5"] = {
				0.2, -- [1]
				1, -- [2]
				1, -- [3]
			},
			["UseNameplateHandoff"] = true,
			["SpecialWarningFlashAlph4"] = 0.4,
			["SpecialWarningFlashCol1"] = {
				1, -- [1]
				1, -- [2]
				0, -- [3]
			},
			["DontShowPTCountdownText"] = false,
			["PTCountThreshold2"] = 5,
			["SpecialWarningFlashCount2"] = 1,
			["AFKHealthWarning"] = false,
			["EventSoundDungeonBGM"] = "None",
			["ForumsMessageShown"] = false,
			["CountdownVoice2"] = "VP:VEM",
			["AutoAcceptGuildInvite"] = false,
			["EnableWBSharing"] = false,
			["ArrowPosX"] = 0,
			["SpecialWarningSound"] = 8174,
			["AITimer"] = true,
			["SpecialWarningFlashDura3"] = 1,
			["WarningShortText"] = true,
			["DontShowSpecialWarningText"] = false,
			["SpecialWarningSound3"] = "Interface\\AddOns\\DBM-Core\\sounds\\AirHorn.ogg",
			["SpecialWarningFlash4"] = false,
			["StripServerName"] = true,
			["ShowGuildMessages"] = false,
			["DisableSFX"] = false,
			["AutologBosses"] = false,
			["SpecialWarningFlashDura4"] = 0.7,
			["WarningPoint"] = "TOP",
			["LatencyThreshold"] = 250,
			["SpecialWarningFlashCol3"] = {
				1, -- [1]
				0, -- [2]
				0, -- [3]
			},
			["WarningColors"] = {
				{
					["r"] = 0.4117647058823529,
					["g"] = 0.8,
					["b"] = 0.9411764705882353,
				}, -- [1]
				{
					["r"] = 0.9490196078431372,
					["g"] = 0.9490196078431372,
					["b"] = 0,
				}, -- [2]
				{
					["r"] = 1,
					["g"] = 0.5019607843137255,
					["b"] = 0,
				}, -- [3]
				{
					["r"] = 1,
					["g"] = 0.1019607843137255,
					["b"] = 0.1019607843137255,
				}, -- [4]
			},
			["SpecialWarningSound4"] = 9278,
			["SWarningAlphabetical"] = true,
			["SpecialWarningSound2"] = 15391,
			["BlockNoteShare"] = true,
			["SpecialWarningFlash5"] = false,
			["SpecialWarningFlashDura5"] = 1,
			["DontPlaySpecialWarningSound"] = true,
			["ModelSoundValue"] = "",
			["DontPlayTrivialSpecialWarningSound"] = true,
			["SpecialWarningFlash2"] = false,
			["WarningY"] = -198.5001831054688,
			["RangeFrameRadarPoint"] = "BOTTOMLEFT",
			["DontShowInfoFrame"] = true,
			["HideTooltips"] = false,
			["AdvancedAutologBosses"] = false,
			["RangeFrameUpdates"] = "Average",
			["MovieFilter2"] = "OnlyFight",
			["RoleSpecAlert"] = false,
			["RaidWarningSound"] = "",
			["CustomSounds"] = 0,
			["SilentMode"] = false,
			["SpecialWarningFlashCount3"] = 3,
			["ShortTimerText"] = true,
			["WhisperStats"] = false,
			["VoiceOverSpecW2"] = "DefaultOnly",
			["LogOnlyNonTrivial"] = true,
			["DontPlayPTCountdown"] = false,
			["SpecialWarningFlashAlph5"] = 0.5,
			["SpecialWarningDuration2"] = 1.5,
			["WarningIconLeft"] = true,
			["RangeFrameSound1"] = "none",
			["ShowEngageMessage"] = false,
			["RangeFrameLocked"] = false,
			["ArrowPosY"] = -150,
			["WarningFontSize"] = 20,
			["EventSoundVictory2"] = "None",
			["SpecialWarningFlashDura2"] = 0.4,
			["LastRevision"] = 0,
			["GUIPoint"] = "TOPLEFT",
			["SettingsMessageShown"] = true,
			["SWarnClassColor"] = true,
			["SpecialWarningFlashCount5"] = 3,
			["SpecialWarningPoint"] = "CENTER",
			["InfoFrameLines"] = 0,
			["DontSetIcons"] = true,
			["BigBrotherAnnounceToRaid"] = false,
			["DontShowBossAnnounces"] = false,
			["CountdownVoice"] = "VP:VEM",
			["InfoFrameFontSize"] = 12,
			["CountdownVoice3"] = "VP:VEM",
			["DontShowUserTimers"] = false,
			["SpecialWarningFlashCol4"] = {
				1, -- [1]
				0, -- [2]
				1, -- [3]
			},
			["DontShowRangeFrame"] = false,
			["AutoRespond"] = true,
			["EventDungMusicMythicFilter"] = true,
			["GUIY"] = -50.99998474121094,
			["RangeFrameFrames"] = "radar",
			["DontPlayCountdowns"] = false,
			["ShowBigBrotherOnCombatStart"] = false,
			["SpecialWarningIcon"] = true,
			["InfoFrameFont"] = "Interface\\AddOns\\ElvUI\\Media\\Fonts\\Expressway.ttf",
			["SpecialWarningFlashAlph1"] = 0.3,
			["ShowDefeatMessage"] = true,
			["FilterTankSpec"] = true,
			["WarningDuration2"] = 1.5,
			["WarningFontShadow"] = true,
			["InfoFrameShowSelf"] = false,
			["SpecialWarningFont"] = "Interface\\AddOns\\ElvUI\\Media\\Fonts\\Expressway.ttf",
			["DontRestoreRange"] = false,
			["SpecialWarningFlash1"] = false,
			["DontShowBossTimers"] = false,
			["SpecialWarningFontStyle"] = "THICKOUTLINE",
			["DontShowSpecialWarningFlash"] = true,
			["DisableStatusWhisper"] = false,
			["RecordOnlyBosses"] = false,
			["WorldBossNearAlert"] = false,
			["WarningX"] = 0,
			["BadIDAlert"] = false,
			["SpecialWarningFlashCount4"] = 2,
			["AutoAcceptFriendInvite"] = false,
			["WarningIconChat"] = true,
			["SpecialWarningFlashCount1"] = 1,
			["HideGuildChallengeUpdates"] = false,
			["SpecialWarningSound5"] = 128466,
			["DontSendYells"] = false,
			["ShowPizzaMessage"] = false,
			["RangeFrameSound2"] = "none",
			["GUIHeight"] = 700,
			["SpecialWarningFlash3"] = false,
			["SpecialWarningY"] = 255.0002136230469,
			["Enabled"] = true,
			["InfoFrameX"] = -415.4991760253906,
			["GUIWidth"] = 900,
			["FilterVoidFormSay"] = true,
			["AutoReplySound"] = false,
			["RLReadyCheckSound"] = true,
			["FilterTrashWarnings2"] = true,
			["GUIX"] = 13.00035667419434,
			["EventSoundMusic"] = "None",
			["FilterInterrupt2"] = "TandFandBossCooldown",
			["DisableGuildStatus"] = false,
			["DebugLevel"] = 1,
			["SpecialWarningFlashDura1"] = 0.4,
			["InfoFrameLocked"] = false,
			["SpecialWarningFlashAlph2"] = 0.3,
			["HelpMessageVersion"] = 3,
		},
	}
	DBM_MinimapIcon = {
		["hide"] = true,
	}
	DBT_AllPersistentOptions = {
		["Luckyone"] = {
			["DBM"] = {
				["FontSize"] = 12,
				["HugeTimerY"] = -248.9997100830078,
				["TDecimal"] = 5,
				["Scale"] = 1,
				["IconLeft"] = true,
				["TimerY"] = -219.5001525878906,
				["IconRight"] = false,
				["ClickThrough"] = true,
				["HugeAlpha"] = 0.800000011920929,
				["Texture"] = "Interface\\Buttons\\WHITE8X8",
				["HugeWidth"] = 273,
				["EnlargeBarTime"] = 10,
				["TimerPoint"] = "CENTER",
				["HugeBarYOffset"] = 1,
				["Font"] = "Interface\\AddOns\\ElvUI\\Media\\Fonts\\Expressway.ttf",
				["FontFlag"] = "OUTLINE",
				["Height"] = 20,
				["Width"] = 167,
				["HugeTimerPoint"] = "CENTER",
				["InlineIcons"] = false,
				["Spark"] = false,
				["TimerX"] = -241.5001678466797,
				["HugeTimerX"] = 12.00008869171143,
				["HugeScale"] = 1,
				["BarXOffset"] = 0,
				["BarYOffset"] = 1,
			},
		},
	}

	DBM:ApplyProfile("Luckyone")

end
