name: Release

on:
  push:
    tags:
      - '**'
    paths-ignore:
      - '.github/**'

jobs:
    release:
      runs-on: ubuntu-22.04

      environment: packager

      env:
        CF_API_KEY: ${{ secrets.CF_API_KEY }}
        WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}

      steps:
        - name: Clone project
          uses: actions/checkout@v4

        - name: BigWigsPackager
          uses: BigWigsMods/packager@v2
          with:
            args: -n "{package-name}-{project-version}"